name: bikehandling
channels:
  - conda-forge
  - moorepants
dependencies:
  - python=2.7.*
  - ipython
  - numpy
  - scipy <0.19  # nanmean was deprecated
  - matplotlib
  - pyyaml
  - uncertainties
  - dynamicisttoolkit
  - pytables <3.0
  - pip:
    - BicycleParameters
    - git+https://github.com/moorepants/BicycleDataProcessor.git@kresie-updates
    - yeadon  # this will not try to install mayavi but the conda-forge package will
