name: bikehandling
channels:
  - conda-forge
  - moorepants
dependencies:
  - python =2.7.*
  - ipython
  - libgfortran =1  # NOTE : May need to be removed for Windows.
  - numpy =1.8.*
  - scipy =0.13.*
  - matplotlib
  - pytables <3.0
  - pyyaml
  - uncertainties
  - dynamicisttoolkit >=0.3.4
  - pip:
    - yeadon  # this will not try to install mayavi but the conda-forge package will
    - BicycleParameters >=0.2.0
